force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Collaboration_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Opportunity__c</fullName>
    <label>Collaboration Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Sample_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Date_Samples_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Samples_Received__c</fullName>
    <label>Samples Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Forecasted_Number_of_Samples__c.field-meta.xml
<CustomField>
    <fullName>Forecasted_Number_of_Samples__c</fullName>
    <label>Samples Forecasted</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Received__c.field-meta.xml
<CustomField>
    <fullName>Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sample_Received_Stage__c/Sample_Received_Stage__c.object-meta.xml
<CustomObject>
    <label>Sample Received Stage</label>
    <nameField>
        <displayFormat>Sample-{00000}</displayFormat>
        <label>Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Received Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Received_Stage__c/fields/Collaboration_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaboration Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sample Received Stage</relationshipLabel>
    <relationshipName>Sample_Received_Stage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Received_Stage__c/fields/Recivied_Date__c.field-meta.xml
<CustomField>
    <fullName>Recivied_Date__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchSampleReceivedHandler.cls
/*Description : - Get Sample recieved Date on Batch object based on Sample Received
  Author : - Sunny/Ramya
  Date Created : - 01/16/2025
 */

public class BatchSampleReceivedHandler {
    Public static void sampleRecieved(List<Sample_Received_Stage__c> sampleRecords){
        System.debug('Triggered');
       if (sampleRecords == null || sampleRecords.isEmpty()) {
            return; 
        }
        //Get Related Opportunity
        Set<Id> OpportunityID = new Set<Id>();
        if(sampleRecords!=null){
        for(Sample_Received_Stage__c SR : sampleRecords){
            OpportunityID.add(SR.Collaboration_Opportunity__c);
        }}
        //Get All the Batches related to Opportunity
        List<Batch__c> BatchList = [Select id,Collaboration_Opportunity__c,CreatedDate,name,Forecasted_Number_of_Samples__c 
                                   from Batch__c 
                                   where Collaboration_Opportunity__c IN: OpportunityID 
                                   ORDER BY CreatedDate ];
        Map<Integer,Decimal> BatchQuantityMap = new Map<Integer,Decimal>();
        Map<Integer,Id> BatchIDMap = new Map<Integer,Id>();
        Decimal Sum = 0;
        Integer Count = 0;
        if(BatchList != null){
        for(Batch__c bt: BatchList ){
            Count++;
            if(bt.Forecasted_Number_of_Samples__c !=null){
            	Sum = bt.Forecasted_Number_of_Samples__c + Sum;
            	BatchQuantityMap.put(Count,Sum);
            	BatchIDMap.put(Count,bt.Id);
            }
        }}
        Integer Counter2=0;
        Map<Integer,Decimal> SampleRMap = new Map<Integer,Decimal>();
        Map<Integer,Date> SRDateMap = new Map<Integer,Date>();
        List<Sample_Received_Stage__c> SampleReceivedList = [Select id,Collaboration_Opportunity__c,Recivied_Date__c,Quantity__c 
                                                             from Sample_Received_Stage__c 
                                                             where Collaboration_Opportunity__c IN : OpportunityID 
                                                             ORDER BY Recivied_Date__c ];
        Decimal SumSR = 0;
        For(Sample_Received_Stage__c sr: SampleReceivedList)   {
            Counter2++;
            if(sr.Quantity__c != null){
            	SumSR = SumSR + sr.Quantity__c;
            	SampleRMap.put(Counter2,SumSR);
            	SRDateMap.put(Counter2,sr.Recivied_Date__c);
            }
        } 
        
        //Comparing Batch Quantities and Sample received Quantities and capturing in Map 
        Map<Id,Date> FinalMap = new Map<Id,Date>();
        for (integer sr :SampleRMap.keySet() ){
            for(integer b :BatchQuantityMap.keySet()){
                if(SampleRMap.get(sr) >= BatchQuantityMap.get(b)){
                    if(!FinalMap.containsKey(BatchIDMap.get(b))){
                        FinalMap.put(BatchIDMap.get(b),SRDateMap.get(sr));
                      } 
                 } 
             }
        }    
        for(Integer i : BatchIDMap.keySet()){
            if(!FinalMap.containsKey(BatchIDMap.get(i))){
                        FinalMap.put(BatchIDMap.get(i),null);
                      } 
            
        }
          
        List<Batch__c> BatchrecordsToUpdate = new List<Batch__c>();
        for(Batch__c  b : BatchList){
            if(FinalMap.containsKey(b.Id)){
                b.Date_Samples_Received__c = FinalMap.get(b.Id);
                if(Finalmap.get(b.Id)!= null){
                    b.Received__c = true;
                }
                Else {
                    b.Received__c = false;
                }
                
                BatchrecordsToUpdate.add(b)  ;            
            }
         }
        
        //Updating Batches
        if (!BatchrecordsToUpdate.isEmpty()) {
            try {
                update BatchrecordsToUpdate;
            } catch (DmlException ex) {
                System.debug('Error updating Batch records: ' + ex.getMessage());
            }
        }
      }
}