force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Collaboration_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Opportunity__c</fullName>
    <label>Collaboration Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Sample_Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Date_Samples_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Samples_Received__c</fullName>
    <label>Samples Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Forecasted_Number_of_Samples__c.field-meta.xml
<CustomField>
    <fullName>Forecasted_Number_of_Samples__c</fullName>
    <label>Samples Forecasted</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Received__c.field-meta.xml
<CustomField>
    <fullName>Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sample_Received_Stage__c/Sample_Received_Stage__c.object-meta.xml
<CustomObject>
    <label>Sample Received Stage</label>
    <nameField>
        <displayFormat>Sample-{00000}</displayFormat>
        <label>Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Received Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Received_Stage__c/fields/Collaboration_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaboration Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sample Received Stage</relationshipLabel>
    <relationshipName>Sample_Received_Stage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Received_Stage__c/fields/Recivied_Date__c.field-meta.xml
<CustomField>
    <fullName>Recivied_Date__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchSampleReceivedHandlerTest.cls
@isTest
public class BatchSampleReceivedHandlerTest {
    @testSetup
    static void setupTestData() {
        
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today()
        );
        insert testOpportunity;

        
        List<Batch__c> batchList = new List<Batch__c>();
        for (Integer i = 0; i < 3; i++) {
            batchList.add(new Batch__c(
                Name = 'Batch ' + i,
                Collaboration_Opportunity__c = testOpportunity.Id,
                Forecasted_Number_of_Samples__c = 10
            ));
        }
        insert batchList;

      
        List<Sample_Received_Stage__c> sampleList = new List<Sample_Received_Stage__c>();
        for (Integer i = 0; i < 3; i++) {
            sampleList.add(new Sample_Received_Stage__c(
                Collaboration_Opportunity__c = testOpportunity.Id,
                Recivied_Date__c = Date.today().addDays(i),
                Quantity__c = 10
            ));
        }
        insert sampleList;
    }

    @isTest
    static void testSampleReceived() {
       
        List<Sample_Received_Stage__c> testSamples = [SELECT Id, Collaboration_Opportunity__c FROM Sample_Received_Stage__c];
        List<Batch__c> testBatches = [SELECT Id, Date_Samples_Received__c, Received__c FROM Batch__c];

        Test.startTest();
        BatchSampleReceivedHandler.sampleRecieved(testSamples);
        Test.stopTest();

        List<Batch__c> updatedBatches = [SELECT Id, Date_Samples_Received__c, Received__c FROM Batch__c];
        System.assertEquals(3, updatedBatches.size(), 'All batches should be updated');
        for (Batch__c b : updatedBatches) {
            System.assertNotEquals(null, b.Date_Samples_Received__c, 'Date_Samples_Received__c should be set');
            System.assertEquals(true, b.Received__c, 'Received__c should be true');
        }
    }
}