force-app/main/default/objects/Account/fields/Country_global__c.field-meta.xml
<CustomField>
    <fullName>Country_global__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/US_Non_US__c.field-meta.xml
<CustomField>
    <fullName>US_Non_US__c</fullName>
    <label>US/Non-US</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-US</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/All_RCA_Components_Completed__c.field-meta.xml
<CustomField>
    <fullName>All_RCA_Components_Completed__c</fullName>
    <description>Added &quot;Date&quot; to field label JG April 2020</description>
    <inlineHelpText>Date all components of the RCA are complete, move to Collaboration Signoff</inlineHelpText>
    <label>All RCA Components Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Budget_Agreement__c</fullName>
    <description>Status -critical for notifications, dashboards and reports

Formerly &quot;Budget Agreement&quot; changed by JG April 2020</description>
    <label>Budget Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>D Not Applicable</fullName>
                <isActive>false</isActive>
                <label>D Not Applicable</label>
            </value>
            <value>
                <fullName>D Not Started</fullName>
                <isActive>false</isActive>
                <label>D Not Started</label>
            </value>
            <value>
                <fullName>Sr. Mgmnt. Approved</fullName>
                <isActive>false</isActive>
                <label>Sr. Mgmnt. Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget_Itemization_Information_Available__c.field-meta.xml
<CustomField>
    <fullName>Budget_Itemization_Information_Available__c</fullName>
    <description>Formerly Budget Itemization Information Available, changed by JG April 2020</description>
    <label>Budget Itemization Info Available Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Collaboration_Agreement_ready_for_Legal__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Agreement_ready_for_Legal__c</fullName>
    <description>Formerly &quot;RCA Ready for Legal Review&quot; changed by JG April 2020</description>
    <label>RCA Finalized Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Funds_Available__c.field-meta.xml
<CustomField>
    <fullName>Funds_Available__c</fullName>
    <description>Previously &quot;Funds Available&quot; changed by JG April 2020</description>
    <label>Budget Assessment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ICFs_Available__c.field-meta.xml
<CustomField>
    <fullName>ICFs_Available__c</fullName>
    <label>ICFs Available Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ICFs_Ready_for_Legal_Review__c.field-meta.xml
<CustomField>
    <fullName>ICFs_Ready_for_Legal_Review__c</fullName>
    <description>Previously &quot;ICFs Ready for Legal Review&quot; Changed by JG April 2020</description>
    <label>ICF Certification Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Informed_Consent_Forms_Approved__c.field-meta.xml
<CustomField>
    <fullName>Informed_Consent_Forms_Approved__c</fullName>
    <description>Formerly &quot;Informed Consent Forms Approved&quot; changed by JG April 2020</description>
    <label>ICF Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PBO_Associate__c.field-meta.xml
<CustomField>
    <fullName>PBO_Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agreement Associate</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.PBO_Associate__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proceed_Based_on_Initial_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Proceed_Based_on_Initial_Assessment__c</fullName>
    <description>Formerly &quot;Proceed Based on Initial Assessment&quot; - changed by JG April 2020</description>
    <label>Assessment Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proceed_Based_on_Research_Plan__c.field-meta.xml
<CustomField>
    <fullName>Proceed_Based_on_Research_Plan__c</fullName>
    <description>Formerly &quot;Proceed Based on Research Plan&quot; - changed by JG April 2020</description>
    <inlineHelpText>Date approved at ROP to move to the Agreement stage</inlineHelpText>
    <label>Research Plan Reviewed at ROP Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RCA_Signatures__c.field-meta.xml
<CustomField>
    <fullName>RCA_Signatures__c</fullName>
    <description>Status -critical for notifications, dashboards and reports</description>
    <label>RCA Signatures</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Research_Plan_Finalized__c.field-meta.xml
<CustomField>
    <fullName>Research_Plan_Finalized__c</fullName>
    <description>Formerly &quot;Research Plan Finalized&quot; changed by JG April 2020</description>
    <label>Final Research Plan Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RPR_Final_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>RPR_Final_Approval_Date__c</fullName>
    <description>Date RGC has signed off

Formerly &quot;Opportunity Approved Date&quot; changed by JG April 2020</description>
    <inlineHelpText>Date Collaboration approved to move to Signatures and Execution stage.</inlineHelpText>
    <label>CV Signoff at ROP Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Sheet_Agreed__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet_Agreed__c</fullName>
    <description>Added &quot;Date&quot; to field label JG April 2020</description>
    <label>Term Sheet Agreed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_Sheet_agreed_by_RGC_LT__c.field-meta.xml
<CustomField>
    <fullName>Term_Sheet_agreed_by_RGC_LT__c</fullName>
    <description>Added &quot;Date&quot; to field label JG April 2020</description>
    <label>Term Sheet Agreed by RGC LT Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/US_Non_US__c.field-meta.xml
<CustomField>
    <fullName>US_Non_US__c</fullName>
    <description>US vs Non- US sample origin - required for automated ABAC notification workflows</description>
    <label>US/Non-US</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-US</fullName>
                <default>true</default>
                <label>Non-US</label>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PBO_Associate__c.field-meta.xml
<CustomField>
    <fullName>PBO_Associate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agreement Associate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States of America</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension</fullName>
    </customValue>
    <customValue>
        <fullName>Ashmore and Cartier Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Baker Island</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Bassas Da India</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResearchPlanSuccessfullyProcess_Test.cls
@isTest
public class ResearchPlanSuccessfullyProcess_Test {
        @testSetup static void testSetup() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'RGC Power User'];
        User testRGCUser = new User ( Alias = 'RGCPU1', Email = 'testRGCPower@rgcpowerusertest.com',
                                EmailEncodingKey = 'UTF-8', LastName = 'poweruserRGC', LanguageLocaleKey = 'en_US',
                                LocaleSidKey = 'en_US', ProfileId = p.Id,
                                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testRGCPower@rgcpowerusertest.com');
        insert testRGCUser;
        User testRGCPowerUser = new User ( Alias = 'RGCPU2', Email = 'testRGCPowerUser@rgcpowerusertest.com',
                                EmailEncodingKey = 'UTF-8', LastName = 'powerRGCUser', LanguageLocaleKey = 'en_US',
                                LocaleSidKey = 'en_US', ProfileId = p.Id, PBO_Associate__c = true,
                                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testRGCPowerUser@rgcpowerusertest.com');
        insert testRGCPowerUser;                
        Account a = new Account ( Name = 'testInstitution',
                                  Country_global__c = 'United States of America',
                                  US_Non_US__c = 'Non-US');
        insert a;   
        }
    @isTest
    private static void ResearchPlanSuccessfullyProcess_MethodTest(){
        Account at = [SELECT Id, Country_global__c,US_Non_US__c  FROM Account WHERE Name = 'testInstitution' Limit 1];
        User userRGC = [SELECT Id,PBO_Associate__c  FROM User WHERE Username = 'testRGCPowerUser@rgcpowerusertest.com' Limit 1];
        Id opRecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Single Institution Collaboration Opportunity').getRecordtypeID();
        Opportunity opt = new Opportunity(RecordTypeId = opRecordTypeID, name = 'Test Opty',
                                          StageName = 'Early Discussions', CloseDate = date.today() + 11,
                                          PBO_Associate__c = userRGC.id,
                                          Budget_Agreement__c = 'Completed',RPR_Final_Approval_Date__c = date.today(),
                                          RCA_Signatures__c = 'Completed',Funds_Available__c = date.today(),
                                          Budget_Itemization_Information_Available__c = date.today(),
                                          ICFs_Ready_for_Legal_Review__c = date.today(),
                                          Collaboration_Agreement_ready_for_Legal__c =  date.today(),
                                          Proceed_Based_on_Initial_Assessment__c = date.today(),
                                          Proceed_Based_on_Research_Plan__c  = date.today(),
                                          Term_Sheet_Agreed__c = date.today(),
                                          Informed_Consent_Forms_Approved__c  = date.today(),
                                          Research_Plan_Finalized__c = date.today(),
                                          All_RCA_Components_Completed__c = date.today(),
                                          Term_Sheet_agreed_by_RGC_LT__c = date.today(),
                                          ICFs_Available__c = date.today()
                                         );
        insert opt;
    }
}