force-app/main/default/objects/Account/fields/Country_global__c.field-meta.xml
<CustomField>
    <fullName>Country_global__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/US_Non_US__c.field-meta.xml
<CustomField>
    <fullName>US_Non_US__c</fullName>
    <label>US/Non-US</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-US</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States of America</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension</fullName>
    </customValue>
    <customValue>
        <fullName>Ashmore and Cartier Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Baker Island</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Bassas Da India</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetLogoURLTest.cls
@isTest(SeeAllData = false)
public class GetLogoURLTest {
    @TestSetup
    private static void setup() {
        Account acc = new Account(Name='Test',Phone='768778687',Country_global__c='United States of America',US_Non_US__c='US', Website= 'https://www.google.com/');
        insert acc;
    }
    @isTest
    static void testAccountCreation() {
        Account accRec = [SELECT Id, Website FROM Account WHERE Name = 'Test'];
        Set<Id> accIDSet = new Set<Id>();
        accIDSet.add(accRec.Id);
        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new ExampleCalloutMock());
        HttpRequest request = new HttpRequest();
        String websiteURL= accRec.Website;
        System.debug('websiteURL---------->'+websiteURL);
        String endpointurl = 'https://logo.clearbit.com/'+websiteURL;
        request.setEndpoint(endpointurl);
        GetLogoURL.mockRequest = request;
        GetLogoURL.fetchLogoUrl(accIDSet);   
        Test.stopTest();
    }
    
    @isTest
    static void testAccountUpdate() {
        Account accRec = [SELECT Id, Website FROM Account WHERE Name = 'Test'];
        accRec.Website = 'https://www.tecsalud.mx/';
        update accRec;
        Set<Id> accIDSet = new Set<Id>();
        accIDSet.add(accRec.Id);
        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new ExampleCalloutMock());
        HttpRequest request = new HttpRequest();
        String websiteURL= accRec.Website;
        System.debug('websiteURL---------->'+websiteURL);
        String endpointurl = 'https://logo.clearbit.com/'+websiteURL;
        request.setEndpoint(endpointurl);
        GetLogoURL.mockRequest = request;
        GetLogoURL.fetchLogoUrl(accIDSet);    
        Test.stopTest();
    }
    
}