force-app/main/default/objects/Account/fields/Country_global__c.field-meta.xml
<CustomField>
    <fullName>Country_global__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/US_Non_US__c.field-meta.xml
<CustomField>
    <fullName>US_Non_US__c</fullName>
    <label>US/Non-US</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-US</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <description>Type of Agreement</description>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RCA - Research Collaboration Agreement</fullName>
            </value>
            <value>
                <fullName>MTA - Material Transfer Agreements</fullName>
            </value>
            <value>
                <fullName>SA - Sequencing Agreement</fullName>
            </value>
            <value>
                <fullName>DSA - Data Sharing Agreement</fullName>
            </value>
            <value>
                <fullName>RSA - Results Sharing Agreement</fullName>
            </value>
            <value>
                <fullName>CA - Collaboration Agreement</fullName>
            </value>
            <value>
                <fullName>FA - Funding Agreement</fullName>
            </value>
            <value>
                <fullName>MCRU - Master Clinical Research Unit Agreement</fullName>
            </value>
            <value>
                <fullName>RPI - Regeneron Pharmaceuticals, Inc</fullName>
            </value>
            <value>
                <fullName>Consort - Consortium Agreement</fullName>
            </value>
            <value>
                <fullName>External Dataset</fullName>
            </value>
            <value>
                <fullName>RCA - Other</fullName>
            </value>
            <value>
                <fullName>Other Agreement Type</fullName>
            </value>
            <value>
                <fullName>DUA</fullName>
                <isActive>false</isActive>
                <label>DUA - Data Use Agreement / Data Access Agreement / Information Transfer Agreement / Data Sharing Agreement / Data Transfer Agreement</label>
            </value>
            <value>
                <fullName>RCA - Custom Agreement (Term Sheet)</fullName>
                <isActive>false</isActive>
                <label>RCA - Custom Agreement (Term Sheet)</label>
            </value>
            <value>
                <fullName>RCA - Domestic Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - Domestic Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - Domestic No Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - Domestic No Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - EU Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - EU Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - EU No Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - EU No Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - Large Scale Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - Large Scale Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - Large Scale No Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - Large Scale No Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - ROW Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - ROW Budget Agreement</label>
            </value>
            <value>
                <fullName>RCA - ROW No Budget Agreement</fullName>
                <isActive>false</isActive>
                <label>RCA - ROW No Budget Agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Budget_Agreement__c</fullName>
    <description>Status -critical for notifications, dashboards and reports

Formerly &quot;Budget Agreement&quot; changed by JG April 2020</description>
    <label>Budget Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>D Not Applicable</fullName>
                <isActive>false</isActive>
                <label>D Not Applicable</label>
            </value>
            <value>
                <fullName>D Not Started</fullName>
                <isActive>false</isActive>
                <label>D Not Started</label>
            </value>
            <value>
                <fullName>Sr. Mgmnt. Approved</fullName>
                <isActive>false</isActive>
                <label>Sr. Mgmnt. Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Budget_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Budget_Assessment__c</fullName>
    <description>Status - critical for notifications,dashboards and reports</description>
    <label>Budget Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
                <default>true</default>
                <label>Not Applicable</label>
            </value>
            <value>
                <fullName>Not Reviewed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Need More Info</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Collaborator_Key__c.field-meta.xml
<CustomField>
    <fullName>Collaborator_Key__c</fullName>
    <externalId>true</externalId>
    <label>Collaborator Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Geographic_Area__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Area__c</fullName>
    <label>Geographic Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>European Union</fullName>
            </value>
            <value>
                <fullName>Rest of World</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/US_Non_US__c.field-meta.xml
<CustomField>
    <fullName>US_Non_US__c</fullName>
    <description>US vs Non- US sample origin - required for automated ABAC notification workflows</description>
    <label>US/Non-US</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-US</fullName>
                <default>true</default>
                <label>Non-US</label>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Received_Stage__c/Sample_Received_Stage__c.object-meta.xml
<CustomObject>
    <label>Sample Received Stage</label>
    <nameField>
        <displayFormat>Sample-{00000}</displayFormat>
        <label>Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Received Stage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Received_Stage__c/fields/Collaboration_Key__c.field-meta.xml
<CustomField>
    <fullName>Collaboration_Key__c</fullName>
    <label>Collaboration Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Received_Stage__c/fields/Recivied_Date__c.field-meta.xml
<CustomField>
    <fullName>Recivied_Date__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States of America</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Ascension</fullName>
    </customValue>
    <customValue>
        <fullName>Ashmore and Cartier Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Baker Island</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Bassas Da India</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/sampleReciviedProcessingTest.cls
@isTest
public with sharing class sampleReciviedProcessingTest {
    static testmethod void sampleReciviedProcessingRecord() {
        Account Ac = new Account(Name='Test',Phone='768778687',Country_global__c='United States of America',US_Non_US__c='US');
        Opportunity Op = new Opportunity(Name='Op1',AccountId=Ac.Id,StageName='7- Active',CloseDate=System.Today(),Collaborator_Key__c='DRIFT-NIMH',Budget__c='Budget',Agreement_Type__c='RCA - Research Collaboration Agreement',Geographic_Area__c='Domestic',Budget_Agreement__c='In Progress',Budget_Assessment__c='In Progress');
        insert Op;
        Opportunity Op2 = new Opportunity(Name='Op2',AccountId=Ac.Id,StageName='7- Active',CloseDate=System.Today(),Collaborator_Key__c='CNCD-EXPANSION',Budget__c='Budget',Agreement_Type__c='RCA - Research Collaboration Agreement',Geographic_Area__c='Domestic',Budget_Agreement__c='In Progress',Budget_Assessment__c='In Progress');
        insert Op2;
        String Msg = 'Collaborator,Project Name,Shipment,Num Samples\nDRIFT-NIMH,,9/23/2019,480\nCNCD-EXPANSION,,9/23/2019,22';
        sampleReciviedProcessing.paginationData Records = new sampleReciviedProcessing.paginationData();
        Records =  sampleReciviedProcessing.sampleReciviedProcessingRecord(Msg);
    }
    
    static testmethod void loadDataSampleTest(){
        Account Ac = new Account(Name='Test',Phone='768778687',Country_global__c='United States of America',US_Non_US__c='US');
        Opportunity Op = new Opportunity(Name='Op1',AccountId=Ac.Id,StageName='7- Active',CloseDate=System.Today(),Collaborator_Key__c='DRIFT-NIMH',Budget__c='Budget',Agreement_Type__c='RCA - Research Collaboration Agreement',Geographic_Area__c='Domestic',Budget_Agreement__c='In Progress',Budget_Assessment__c='In Progress');
        insert Op;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'TestData',
            PathOnClient = 'TestData.csv',
            VersionData = Blob.valueOf('Collaborator,Project Name,Shipment,Num Samples\nDRIFT-NIMH,,9/23/2019,480\nCNCD-EXPANSION,,9/23/2019,22'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        
        sampleReciviedProcessing.paginationData loadDataSample = new sampleReciviedProcessing.paginationData();
        loadDataSample = sampleReciviedProcessing.loadDataSample(documents[0].Id);
        
    }
    static testmethod void updateSampleTest(){
        Account Ac = new Account(Name='Test',Phone='768778687',Country_global__c='United States',US_Non_US__c='US');
        Opportunity Op = new Opportunity(Name='Op1',AccountId=Ac.Id,StageName='7- Active',CloseDate=System.Today(),Collaborator_Key__c='DRIFT-NIMH',Budget__c='Budget',Agreement_Type__c='RCA - Research Collaboration Agreement',Geographic_Area__c='Domestic',Budget_Agreement__c='In Progress',Budget_Assessment__c='In Progress');
        insert Op;
        
        Sample_Received_Stage__c St = new Sample_Received_Stage__c(Product__c='test',Quantity__c=5,Recivied_Date__c=System.Today(),Collaboration_Key__c='DRIFT-NIMH',Key__c='Test');
        insert St;
        
        Object Str = JSON.deserializeUntyped('[{"Quantity__c":"2499","Id":"'+Op.id+'"}]');
        string Str2 =  sampleReciviedProcessing.updateSample(Str) ;
    }
    @isTest
    public static void getLatestDataTest(){
        list<String> keySet = New list<String>();
        keySet.add('Test1');
        keySet.add('Test2');
        
        Test.startTest();
        sampleReciviedProcessing.getLatestData(keySet);
        Test.stopTest();
    }
    
}